apiVersion: awsblueprints.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: test-lsi2-dynamodb-table
  namespace: default
spec:
  writeConnectionSecretToRef:
    name: dynamolsi2
  attribute:
    - name: Artist
      type: S
    - name: SongTitle
      type: S
    - name: AlbumTitle
      type: S
  billingMode: PROVISIONED
  localSecondaryIndex:
    - name: AlbumTitleIndex
      nonKeyAttributes:
        - Genre
      projectionType: INCLUDE
      rangeKey: AlbumTitle
  readCapacity: 20
  writeCapacity: 20
  hashKey: Artist
  rangeKey: SongTitle
  region: us-east-1
  tags:
    namespace: team-x
    cluster: crossplane
