apiVersion: awsblueprints.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: test-gsi-dynamodb-table
  namespace: default
spec:
  writeConnectionSecretToRef:
    name: dynamogsi
  attribute:
    - name: UserId
      type: S
    - name: UserName
      type: S
    - name: Pass
      type: B
  billingMode: PROVISIONED
  globalSecondaryIndex:
    - hashKey: UserName
      name: UserNameIndex
      nonKeyAttributes:
        - UserId
      projectionType: INCLUDE
      rangeKey: Pass
      readCapacity: 10
      writeCapacity: 10
  readCapacity: 20
  writeCapacity: 20
  hashKey: UserId
  rangeKey: UserName
  region: us-east-1
  tags:
    namespace: team-x
    cluster: crossplane
