apiVersion: awsblueprints.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: test2-dynamodb-table
  namespace: default
spec:
  writeConnectionSecretToRef:
    name: dynamo2
  attribute:
    - name: UserId
      type: S
  hashKey: UserId
  region: us-east-1
  tags:
    namespace: team-x
    cluster: crossplane
